### ISSUE TITLE
Linking Error on MacOS (10.14.2)

### ISSUE THREAD

**Issue by ErikPartridge** [blas-lapack-rs/blas#30]
When compiling on MacOS using `openblas-src` as the dependency for `blas`, I've been receiving the following errors:

`ld: warning: ignoring file ../libopenblas_haswellp-r0.2.20.a, file was built for archive which is not the architecture being linked (x86_64): ../libopenblas_haswellp-r0.2.20.a
Undefined symbols for architecture x86_64:
  "_caxpby_", referenced from:
     -exported_symbol[s_list] command line option
`

I've attempted to install `openblas` via homebrew as well as via the toml, but I do get the same error either way.

I then proceeded to attempt it with `netlib-src`, which resulted in:

`    ld: warning: ignoring file libVerifyFortran.a, file was built for archive which is not the architecture being linked (x86_64): libVerifyFortran.a
    Undefined symbols for architecture x86_64:
      "_VerifyFortran", referenced from:`

It appears as if there is some general linking error with the library on the latest version on MacOS?

**Comment by IvanUkhov** [comment]
Hi, thanks for the issue. I tried to compile it myself on macOS 10.14.1, and it did work. I’ve also updated OpenBLAS to v0.3.4 (openblas-src v0.7). Do you still get the error?

**Comment by IvanUkhov** [comment]
See also “Usage on macOS” in the [wiki](https://blas-lapack-rs.github.io/usage).
