### ISSUE TITLE
Use system installed BLAS

### ISSUE THREAD

**Issue by mooreryan** [blas-lapack-rs/blas#33]
Sorry if this has been answered somewhere else, but is it possible to use blas and blas-sys without using blas-src?  E.g., using the system installed BLAS or one that I've already compiled?

**Comment by IvanUkhov** [comment]
Sure. `blas` and `blas-sys` do not depend on `blas-src`. One has to do the linking separately. Take a look at this description:

https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki

One could, for instance, take `openblas-src` and activate its [`system`](https://github.com/blas-lapack-rs/openblas-src) feature. The same is available for `netlib-src`, and `accelerate-src` does not require compilation at all.

**Comment by mooreryan** [comment]
Ah thank you!  [This section](https://github.com/blas-lapack-rs/openblas-src#openblas-src----) cleared it up.  I did not notice the bit about Cargo features before you pointed it out.

Thanks!!
